services:
  ros2_vnc:
    privileged: true
    # network_mode: "host"  # DISABLED: Conflicts with VNC - Use port forwarding instead
    ports:
      - "6080:80"      # noVNC web interface
      - "5901:5901"    # VNC server
      - "6699:6699/udp"  # LiDAR MSOP port
      - "7788:7788/udp"  # LiDAR DIFOP port
    volumes:
      # Mount ZED SDK from host (read-only)
      - /usr/local/zed:/usr/local/zed:ro
      # ZED AI models cache
      - ~/.zed_ai_models:/usr/local/zed/resources
    devices:
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyUSB0:/dev/ttyUSB0
      # ZED camera devices (video devices for camera)
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:1
      - ZED_CAMERA_MODEL=zed2i
      - LD_LIBRARY_PATH=/usr/local/zed/lib:$LD_LIBRARY_PATH
    networks:
      - ros2_network
    # Note: Using port forwarding for LiDAR instead of host networking to allow VNC to work
