services:
  ros2_vnc:
    privileged: true
    # network_mode: "host"  # DISABLED: Conflicts with VNC - Use port forwarding instead
    ports:
      - "6080:80"      # noVNC web interface
      - "5901:5901"    # VNC server
      - "6699:6699/udp"  # LiDAR MSOP port
      - "7788:7788/udp"  # LiDAR DIFOP port
    devices:
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:1
    networks:
      - ros2_network
    # Note: Using port forwarding for LiDAR instead of host networking to allow VNC to work
