services:
  ros2_vnc:
    privileged: true
    network_mode: "host"  # Required for LiDAR network access
    devices:
      - /dev/snd:/dev/snd
      - /dev/bus/usb:/dev/bus/usb
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=:1
    # Note: network_mode: host conflicts with 'networks' and 'ports' in base docker-compose.yml
    # The container will use host networking directly
